### ISSUE TITLE
请问如果我想参与开发go-fvm-sdk，该如何入手呢？

### ISSUE THREAD

**Issue by qingfengzxr** [ipfs-force-community/go-fvm-sdk#113]
比如需要哪些前置知识呢？

**Comment by hunjixin** [comment]
你这边是想参与那一块呢,
是打算使用这个写合约呢还是开发sdk呢？

**Comment by qingfengzxr** [comment]
> 
想参与开发SDK

**Comment by qingfengzxr** [comment]
> 你这边是想参与那一块呢, 是打算使用这个写合约呢还是开发sdk呢？
你好，是想参与开发sdk。

**Comment by qingfengzxr** [comment]
> 你这边是想参与那一块呢, 是打算使用这个写合约呢还是开发sdk呢？

你好，是想参与开发sdk。

**Comment by hunjixin** [comment]
1. 可以了解tinygo的用法，了解下tinygo如何转换wasm以及tinygo和go之间的一些差异。
2. 需要了解[ref-fvm](https://github.com/filecoin-project/ref-fvm)项目，本项目编译出来的合约是运行在fvm上面的，基础环境都是基于fvm。
3. 需要有一些filecoin的基础知识，特别是一些内置合约的类型和原理[builtin-actor](https://github.com/filecoin-project/builtin-actors)，这样可以理解fvm提供的一些系统调用的用途。
4. 写一个例子也是很好的入手方法，比如[nft](https://github.com/filecoin-project/FIPs/blob/master/FRCs/frc-0053.md)

**Comment by qingfengzxr** [comment]
> 1. 可以了解tinygo的用法，了解下tinygo如何转换wasm以及tinygo和go之间的一些差异。
> 2. 需要了解[ref-fvm](https://github.com/filecoin-project/ref-fvm)项目，本项目编译出来的合约是运行在fvm上面的，基础环境都是基于fvm。
> 3. 需要有一些filecoin的基础知识，特别是一些内置合约的类型和原理[builtin-actor](https://github.com/filecoin-project/builtin-actors)，这样可以理解fvm提供的一些系统调用的用途。
> 4. 写一个例子也是很好的入手方法，比如[nft](https://github.com/filecoin-project/FIPs/blob/master/FRCs/frc-0053.md)

好的，我去学习一下这些内容，多谢解答

**Comment by Fatman13** [comment]
还有问题的话可以重开。我先关掉这个了。🤝
