### ISSUE TITLE
[待评估] 是否需要早期参与wallaby测试网测试？

### ISSUE THREAD

**Issue by Fatman13** [ipfs-force-community/go-fvm-sdk#73]
## 资源&背景

- wallaby测试网rollout[时间线](https://github.com/filecoin-project/ref-fvm/issues/692)
- 计划每周2更新/迭代一次，直到11月中，寻求社区测试
- filecoin-project/testnet-wallaby 这个repo也有详细介绍
- 暂时完成第一步，self-contained call，不能叫其他的合约

**Comment by web3creator** [comment]
done
